env:
  global:
    - CC_TEST_REPORTER_ID=7390f2da2caa279a5aa7c0580275d37cec8afaac8d543897b57bfb96030c3df0
language: php
php:
  - 7.1
  - 7.2
  - 7.3
  - nightly
before_script:
  - if [[ "$TRAVIS_PHP_VERSION" == "7.1" ]]; then PHPUNIT_FLAGS="--coverage-clover build/logs/clover.xml"; fi
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - composer install --prefer-dist --no-interaction
  - vendor/bin/phpunit tests/ --verbose $PHPUNIT_FLAGS